files: \.*.tf$
repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.75.0 # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
  hooks:
    - id: terraform_fmt
      name: Terraform fmt
      description: Rewrites all Terraform configuration files to a canonical format.
      entry: hooks/terraform_fmt.sh
      language: script
      files: (\.tf|\.tfvars)$
      exclude: \.terraform\/.*$
    - id: terraform_docs
      args:
        - --hook-config=--path-to-file=README.md
    - id: terraform_tflint
      name: Terraform validate with tflint
      description: Validates all Terraform configuration files with TFLint.
      require_serial: true
      entry: hooks/terraform_tflint.sh
      language: script
      files: (\.tf|\.tfvars)$
      exclude: \.terraform\/.*$

    - id: terraform_validate
      name: Terraform validate
      description: Validates all Terraform configuration files.
      require_serial: true
      entry: hooks/terraform_validate.sh
      language: script
      files: (\.tf|\.tfvars)$
      exclude: \.terraform\/.*$

    - id: terraform_checkov
      name: Checkov
      description: Runs checkov on Terraform templates.
      entry: hooks/terraform_checkov.sh
      language: script
      always_run: false
      files: \.tf$
      exclude: \.terraform\/.*$
      require_serial: true

    - id: terraform_providers_lock
      name: Lock terraform provider versions
      description: Updates provider signatures in dependency lock files.
      require_serial: true
      entry: hooks/terraform_providers_lock.sh
      language: script
      files: (\.terraform\.lock\.hcl)$
      exclude: \.terraform\/.*$

    # - id: infracost_breakdown
    #   name: Infracost breakdown
    #   description: Check terraform infrastructure cost
    #   entry: hooks/infracost_breakdown.sh
    #   language: script
    #   require_serial: true
    #   files: \.(tf|hcl)$
    #   exclude: \.terraform\/.*$

    # - id: terraform_tfsec
    #   name: Terraform validate with tfsec
    #   description: Static analysis of Terraform templates to spot potential security issues.
    #   require_serial: true
    #   entry: hooks/terraform_tfsec.sh
    #   language: script

